---
title: "Homework 1"
output: html_document
---

## Instructions

Please complete this assignment by creating a new RMarkdown (or RNotebook or Quarto) file (one that has the extension .Rmd or .qmd). Be sure to include your name in the preamble. Please submit both your .Rmd/.qmd and your .html files to Canvas.

#### Formatting

- All code should be in a code chunk (gray boxes)
- All text (as in, interpretations/opinions/summary statements etc.) should be *outside* the code chunks. 
- You may make comments in your code within the code chunks. However, no long form sentences should be in there.
- Make use of headers! Question number should be the #1 header (use one `#` symbol, then a space, then type "Question 1"). You may use subheaders (meaning more than 1 `#` symbol) for different parts of the question, if you wish. However, your interpretations/opinions/summary statements should not be contained within a header (that is, there should be no `#` symbols preceding it).

You are allowed to Google things. *However*, if you use code from an outside source (meaning not the lecture slides or the R help documentation), then you must provide a **working link** to the website you used. You don't need to use APA formatting or anything. Just a working url. Similarly, you must do the same for any and all AI use (including Chat-GPT). You must include a working link to your conversation.

All homeworks are **independent projects**. You may not share code or answers with your peers, but you can discuss them in broad strokes. You absolutely should **not simply copy someone else’s code**. If we believe one student has copied another’s work, both students will receive a 0 on the homework assignment. If you wind up working or consulting with a peer, please list them on your assignment (the equivalent of citing their work).

In the instructions, when it says **_by hand_**, what we mean is that you should not use a function that is built into R to complete the task. For example, if I ask you to find the mean *by hand*, you should **not** use the `mean()` function. However, you can (and should!) use your variables. So for instance, if I ask you to find the `mean()` by hand, you may do something like `sum(variableX)/length(variableX)`. This would be an appropriate *by hand* calculation. (You don't need to type `(3 + 5 + 5 + 17) / 4`...you can still use your variables). If we do *not* specify *by hand*, then you may of course use a R function.

**Data:** These data were from a study where physical health was predicted by a happiness measure, socioeconomic status, number of close friends, and a 16-week mood intervention with a waitlist control group (coded 0), a positive self affirmation intervention group (coded 1), and a meditation group (coded 2). The data are here: [`th-project-3.csv`](th-project-3.csv)

Good luck!

## Homework Questions

1. Pick 2 of the continuous variables and do the following:
  - Calculate the correlation **by hand**
  - Use a function to calculate the correlation in order to check your work
  - Graph the relationship

2. Given what you found in question 1, do you believe the correlation coefficient that you got? Why or why not?

3. For those same 2 variables, choose one as your outcome measure and one as your predictor.
  - Run a simple linear regression
  - Run a standardized simple linear regression
  - Explain the similarities and differences between your results in question 1 vs. what you see here in question 3
  
4. Pick a 3rd continuous variable. Calculate the partial and semi-partial correlations for the same 2 variables as question 1, controlling for this new continuous variable. Explain the similarities and differences between correlation, partial correlation, semi partial correlation, and regression coefficient.

5. Perform a multiple regression where health is regressed on (predicted by) friends, SES, and happiness. Interpret each regression coefficient (including the intercept). Then interpret the omnibus results. 

6. Graph the (2-d) relationship between health and happiness as found in the above regression. Make sure the association controls for the remaining variables in the model. Include data points in your graph and a confidence band. 

7. Describe why the confidence band looks like a bow tie in the above graph. 

8. Add the group variable `mood.group` into the regression model from #5. Then answer the following:

    a. Interpret the coefficients
    b. Is there a significant increase in variance explained compared to the initial regression in #5? If so, what is the estimate? 

9. Check the assumptions of this regression. Should we trust it?

10. Explain how your lab deals with outliers. Do you agree with the approach? Do you think there are any substantial issues that come with this approach?
